### ISSUE TITLE
Edge computing

### ISSUE THREAD

**Issue by tomlehto** [tomlehto/DS-Himmeli#2]
Implement simple edge computing algorithm for data filtering. Idea is to read sensor value each second, and calculate an average value for the reporting period. E.g. if the period is configured to be 60 seconds, sensor is read 60 times and average of those values is reported.

**Comment by vkarsikk** [comment]
Edge computing magic added. Tomi pls test with real MQTT messaging, I only tested this locally.

**Comment by tomlehto** [comment]
Works well, great job!
